version: "3"
services:

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - /var/log:/var/log
      - /Users/zt/zt_projects/:/var/project/
      - "./promtail-config.yml:/etc/promtail/config.yml"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - fooops
    command: -config.file=/etc/promtail/config.yml

networks:
  fooops:
    driver: "bridge"
