server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "debug"

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchsize: 102400 # <int> | default = 102400]
    batchwait: 5s # <duration> | default = 1s

scrape_configs:
  - job_name: system
    static_configs:
      # - targets:
      #     - localhost
      #   labels:
      #     job: var-log
      #     __path__: /var/log/*.log
      - targets:
          - localhost
        labels:
          job: project-log
          __path__: /var/project/**/*.log
