server:
  http_listen_port: 9080
  grpc_listen_port: 0
  # log_level: "debug"

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://lokiIpAddress:3100/loki/api/v1/push
    batchsize: 102400 # <int> | default = 102400]
    batchwait: 5s # <duration> | default = 1s

scrape_configs:
  - job_name: application
    pipeline_stages:
    - json:
        expressions:
          log: log
          stream: stream
          timestamp: time
    - json:
        expressions:
          level:
          app:
        source: log
    - labels:
        level:
        app:
    static_configs:
      - targets:
        - localhost
        labels:
          job: "^pg12_pg_.+$"
          __path__: /var/lib/docker/containers/{80480c418b9a8bc7b7ec01ea9fa2ce8c68796ac6b750d0bd3290e300649c32ef}/*.log
      - targets:
        - localhost
        labels:
          job: "redis5_redis_1"
          __path__: /var/lib/docker/containers/{5a03ab3e4ad3eef9fdee41d713856b46899eaae56ee59b16d56c485da0717663}/*.log
